events {}

http {

    server {

        listen 8080;

        location / {
            return 302 /desktop/;
        }

        location /desktop/ {
            proxy_pass http://localhost:6080/;
            proxy_set_header Host $host;
        }

        location /vscode/ {
            proxy_pass http://localhost:8081/;
            proxy_set_header Host $host;
        }

        location /terminal/ {
            proxy_pass http://localhost:7681/;
            proxy_set_header Host $host;
        }

        location /files/ {
            proxy_pass http://localhost:8082/;
            proxy_set_header Host $host;
        }

    }
}
