[build]
dockerfile = "Dockerfile"

[deploy]
startCommand = "/startup.sh"
restartPolicyMaxRetries = 5
restartPolicyWindow = 600

[build.buildArg]
BUILDKIT_INLINE_CACHE = "1"

[env]
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
PORT = "3000"
