[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:ssh]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/ssh.err.log
stdout_logfile=/var/log/supervisor/ssh.out.log

[program:postgresql]
command=/etc/init.d/postgresql start
autostart=true
autorestart=true
startsecs=10
stderr_logfile=/var/log/supervisor/postgresql.err.log
stdout_logfile=/var/log/supervisor/postgresql.out.log

[program:redis]
command=/etc/init.d/redis-server start
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/redis.err.log
stdout_logfile=/var/log/supervisor/redis.out.log

[program:nginx]
command=/etc/init.d/nginx start
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:cockpit]
command=/bin/bash -c "systemctl start cockpit || true && sleep infinity"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/cockpit.err.log
stdout_logfile=/var/log/supervisor/cockpit.out.log

[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
